name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        
    - name: install rust
      run: make install
      
    - name: Show Rust versions
      run: make rust-version

    - name: Format code
      run: make format

    - name: Lint code
      run: make lint

    - name: Run tests
      run: make test

    - name: Build release
      run: make release
